#! /usr/bin/env python
import sys, os
os.system("python3 main.py " + str(sys.argv[1]) + " > calendar.md" )
os.system("pandoc -t html5 --css style.css calendar.md -o calendar.pdf")
os.system("zathura calendar.pdf")
